# Generated by Django 4.2.7 on 2025-10-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Required for takeaway orders'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('takeaway', 'Takeaway'), ('dine_in', 'Dine In')], default='dine_in', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, help_text='Required for dine-in orders', max_length=10),
        ),
    ]
